sfURL = r"https://me36117.ap-southeast-1.snowflakecomputing.com/"
sfAccount = "me36117"
sfUser = "RAMASIVA"
sfPassword = "Rama@2022"
sfDatabase = "RAMA_DB"
sfSchema = "PUBLIC"
sfWarehouse = "COMPUTE_WH"
sfRole = "ACCOUNTADMIN"

raw_layer_sf_table = "retail_raw_layer"
cleansed_layer_sf_table ="retail_cleansed_layer"
hive_db = "retail"
raw_layer_hive_table = "raw_layer"
cleansed_layer_hive_table = "cleansed_layer"
raw_layer_df_path =r"outputs\raw_layer.csv"
cleansed_layer_df_path =r"outputs\cleansed_layer.csv"
